const ACTIONS = {
    BALANCE: "BALANCE",
    CHECK_IN: "CHECK_IN",
    PRINT_SUMMARY: "PRINT_SUMMARY"
}

const PASSENGER_TYPE = {
    ADULT: 200,
    SENIOR_CITIZEN: 100,
    KID: 50
}

const SERVICE_FEES = 0.02;

const FARE_DISCOUNT = 0.5;

const STATIONS = ['CENTRAL', 'AIRPORT'];

module.exports = { ACTIONS, PASSENGER_TYPE, SERVICE_FEES, FARE_DISCOUNT, STATIONS };